[dev_setup] Install wget
  Wget is not included in `ubuntu-minimal'. Installing wget before
proceeding enables us to run dev_setup in a debootstrap chroot / jail.

Change-Id: Iff012208f58f9946c64ce27448294af42e558a57

diff --git a/dev_setup/bin/vcap_dev_setup b/dev_setup/bin/vcap_dev_setup
--- a/dev_setup/bin/vcap_dev_setup
+++ b/dev_setup/bin/vcap_dev_setup
@@ -85,6 +85,12 @@ function run_cmd () {
 }
 
 # Check if we have access to the web
+run_cmd apt-get $APT_CONFIG install -qym wget
+if [ $? -ne 0]; then
+  echo "Can't install prerequisite: wget"
+  exit 1
+fi
+
 which wget > /dev/null
 if [ $? -eq 0 ]; then
   echo "Checking web connectivity."
