[dev_setup] Work with broken out repos
  This change adapts dev_setup to the repo split.
  - Cookbooks and bootstrapping scripts are updated.
  - bin/{cc,hm,dea,router,vcap} are removed

  Test plan:
  - Run dev_setup on an existing installation, pass BVT's
  - Run dev_setup on a pristine VM, pass BVt's

  Next step:
  - remove the component / gem sub dirs from vcap repo

Change-Id: If24e2e113075cf0d9135d59b594b3a2517c401fa

diff --git a/dev_setup/bin/vcap_dev_setup b/dev_setup/bin/vcap_dev_setup
--- a/dev_setup/bin/vcap_dev_setup
+++ b/dev_setup/bin/vcap_dev_setup
@@ -15,7 +15,7 @@ OPTIONS:
   -c           deployment config
   -d           cloudfoundry home
   -D           cloudfoundry domain (default: vcap.me)
-  -r           cloud foundry repo
+  -r           cloud foundry repo base
   -b           cloud foundry repo branch/tag/SHA
 EOF
 }
@@ -29,13 +29,15 @@ function run_cmd () {
 }
 
 function clear_bundler_settings () {
+  [ $# -ge 1 ] || return 1
+  local DIR=$1
   # Do we have a Bundler problem?
-  find $CLOUDFOUNDRY_HOME/vcap -type d -name .bundle | grep -Fq .bundle || return 0
+  find $DIR -type d -name .bundle | grep -Fq .bundle || return 0
   if [ "$ALL" != true ]; then
     read -p "Remembered Bundler options could cause you troubles, do you want me to clear them for you? [Y/n]"
     [[ $REPLY =~ ^[nN] ]] && return 0
   fi
-  (cd $CLOUDFOUNDRY_HOME/vcap && find -type d -name .bundle -prune -exec rm -r {} \; )
+  (cd $DIR && find -type d -name .bundle -prune -exec rm -r {} \; )
 }
 
 RUBY="/usr/bin/ruby"
@@ -70,7 +72,7 @@ do
       CLOUDFOUNDRY_DOMAIN=$OPTARG
       ;;
     r)
-      VCAP_REPO=$OPTARG
+      VCAP_REPO_BASE=$OPTARG
       ;;
     b)
       VCAP_REPO_BRANCH=$OPTARG
@@ -90,8 +92,8 @@ if [ -z "$CLOUDFOUNDRY_DOMAIN" ]; then
   CLOUDFOUNDRY_DOMAIN=vcap.me
 fi
 
-if [ -z "$VCAP_REPO" ]; then
-  VCAP_REPO=https://github.com/cloudfoundry/vcap.git
+if [ -z "$VCAP_REPO_BASE" ]; then
+  VCAP_REPO_BASE=https://github.com/cloudfoundry
 fi
 
 if [ -z "$VCAP_REPO_BRANCH" ]; then
@@ -144,19 +146,30 @@ ${GEM} list -i rake -i || sudo ${GEM} install rake -q --no-ri --no-rdoc > /dev/n
 echo "Installing git..."
 run_cmd apt-get $APT_CONFIG install -qym git-core
 
+readonly CORE_REPOS=(cloud_controller dea router stager)
+
 [ -d $CLOUDFOUNDRY_HOME ] || mkdir $CLOUDFOUNDRY_HOME
-if [ ! -d $CLOUDFOUNDRY_HOME/vcap ]; then
-  if ! (cd $CLOUDFOUNDRY_HOME
-    git clone $VCAP_REPO
-    cd vcap
-    git submodule update --init
-    git checkout $VCAP_REPO_BRANCH
-  ); then
-    echo "Unable to clone cloudfoundry repo."
-    exit 1
+for REPO in vcap "${CORE_REPOS[@]}"; do
+  if [ ! -d $CLOUDFOUNDRY_HOME/$REPO ]; then
+    if ! (cd $CLOUDFOUNDRY_HOME
+      git clone --no-checkout $VCAP_REPO_BASE/$REPO
+      cd $REPO
+      git checkout $VCAP_REPO_BRANCH
+      git submodule update --recursive --init
+    ); then
+      echo "Unable to clone cloudfoundry $REPO repo."
+      exit 1
+    fi
+  else
+    clear_bundler_settings $CLOUDFOUNDRY_HOME/$REPO
   fi
-else
-  clear_bundler_settings
+done
+
+
+# Our deployment code needs this gem. Using bundler seems like an overkill for
+# the deployment code. So for now just manually install the required gem.
+if ! gem list rake -i > /dev/null; then
+  gem install rake -q --no-ri --no-rdoc > /dev/null 2>&1
 fi
 
 # Launch chef
