[dev_setup] Enforce 2-space indentation
  Formatting change.

Change-Id: Id222e7b3d125c0313dd922378aa3bc20dd78b2cb

diff --git a/dev_setup/bin/vcap_dev_setup b/dev_setup/bin/vcap_dev_setup
--- a/dev_setup/bin/vcap_dev_setup
+++ b/dev_setup/bin/vcap_dev_setup
@@ -113,11 +113,11 @@ run_cmd apt-get $APT_CONFIG install -qym chef
 run_cmd apt-get $APT_CONFIG install -qym git-core
 [ -d $CLOUDFOUNDRY_HOME ] || mkdir $CLOUDFOUNDRY_HOME
 if [ ! -d $CLOUDFOUNDRY_HOME/vcap ]; then
-   (cd $CLOUDFOUNDRY_HOME && git clone $VCAP_REPO && cd vcap && git submodule update --init && git checkout $VCAP_REPO_BRANCH)
-    if [ $? != 0 ]; then
-      echo "Unable to clone cloudfoundry repo."
-      exit 1
-    fi
+  (cd $CLOUDFOUNDRY_HOME && git clone $VCAP_REPO && cd vcap && git submodule update --init && git checkout $VCAP_REPO_BRANCH)
+  if [ $? != 0 ]; then
+    echo "Unable to clone cloudfoundry repo."
+    exit 1
+  fi
 fi
 
 
